name: Auto Close Completed and Wontfix Issues

on:
  issues:
    types: [labeled]

jobs:
  auto-close:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'completed' || github.event.label.name == 'wontfix'
    permissions:
      issues: write
    steps:
      - name: Close issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "Auto-closing issue with label ${{ github.event.label.name }}"
