name: Auto-close labeled issues
on:
  issues:
    types: [labeled, opened]
jobs:
  close:
    if: github.event.label.name == "completed" || github.event.label.name == "wontfix"
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-close-issue@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
