name: Auto Close Issues
on:
  issues:
    types: [labeled]
jobs:
  close-issue:
    runs-on: ubuntu-latest
    if: github.event.label.name == completed || github.event.label.name == wontfix
    steps:
      - name: Close issue labeled completed or wontfix
        run: echo Closing completed wontfix issue
