name: Auto Close Labeled Issues

on:
  issues:
    types: [labeled]

jobs:
  close-issue:
    if: contains(github.event.label.name, 'completed') || contains(github.event.label.name, 'wontfix')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close Issue
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.issue.number;
            const label = context.payload.label.name;
            if (label === 'completed' || label === 'wontfix') {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                state: 'closed',
                state_reason: label === 'completed' ? 'completed' : 'not_planned'
              });
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: `Automatically closing this issue because it was labeled as **${label}**.`
              });
            }
